import "./root.css"


export const metadata = {
    title: "My App",
    description: "Generated By Aidin",
    viewport: "initial-scale=1, width=device-width"
};

export default function RootLayout ({children}: any) {
    return (
        <html lang="en" className="mother">
            <body className="mother">
                {children}
            </body>
        </html>
        );
}